spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://127.0.0.1:3306/agent?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false'
    username: 'root'
    #password: '!QAZ2wsx'
    password: 'admin'

  ai:
    openai:
      base-url: https://llm.indrin.cn
      api-key: sk-JKenasNCDmGPuJ102JoZTnOnYBxHfgvZkThdeKT4pobuTbBE
      chat:
        enabled: true
        options:
          model: yi-spark
          temperature: 0.7
          max-tokens: 2000
    retry:
      max-attempts: 3
      backoff:
        initial-interval: 1000
        multiplier: 2.0
        max-interval: 10000

logging:
  level:
    com.java.agent: DEBUG
    org.springframework.ai: DEBUG
